# Generated by Django 3.2.3 on 2021-05-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0002_alter_ninjas_dojo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ninjas',
            new_name='ninja',
        ),
    ]
